### ISSUE TITLE
Pill overlaps on app navigation bar elements

### ISSUE THREAD

**Issue by AnonRS3** [samchugit/Immersive_Gestural_Nav_Bar#3]
This may not be able to be solved, since the module sets the pill to be universally immersive, but if there is a bottom navigation bar in an app (such as the Google Play Store), the pill overlaps slightly on the navigation bar. 

Is there a way to possibly set a custom profile (immersive mode on vs off) on a per-app level for this module?

**Comment by Madis0** [comment]
Could the pill just be made invisible (transparent)?

**Comment by AnonRS3** [comment]
There is already a Magisk Module for that, so doing that would take away the point of this one. Unless there was a way to make the pill transparent in specific apps.

**Comment by OswRd** [comment]
![Screenshot_20200103-225303](https://user-images.githubusercontent.com/40842393/71759986-f84ef280-2e7b-11ea-9b68-edd19914eb6d.png)

The navbar is too high when the gboard is un use. Also there's a big black bar between the keyboard and the navbar. This can be fixed?

**Comment by DanGLVK** [comment]
> ![Screenshot_20200103-225303](https://user-images.githubusercontent.com/40842393/71759986-f84ef280-2e7b-11ea-9b68-edd19914eb6d.png)
> 
> The navbar is too high when the gboard is un use. Also there's a big black bar between the keyboard and the navbar. This can be fixed?

it is possible to fix this but you would need to also get rid of the pill (since the pill and keyboard bar are tied to the same value), if you're ok with that just use the fullscreen gestures module

**Comment by DanGLVK** [comment]
> This may not be able to be solved, since the module sets the pill to be universally immersive, but if there is a bottom navigation bar in an app (such as the Google Play Store), the pill overlaps slightly on the navigation bar.
> 
> Is there a way to possibly set a custom profile (immersive mode on vs off) on a per-app level for this module?

this module modifies thes stock system gesture overlays, it's not possible to simply turn them on/off without some sort of app for that, and even then the developer would need to modify his overlays to be new overlays instead of replacing the system ones

**Comment by hung0702** [comment]
> There is already a Magisk Module for that, so doing that would take away the point of this one. Unless there was a way to make the pill transparent in specific apps.

What's the name of that module?

**Comment by DanGLVK** [comment]
@hung0702 that would be fullscreen gestures (it fully gets rid of both the navbar and the pill)

**Comment by ackeecheek** [comment]
Hi can anyone help me?  I've miui 11 in miroom and i installed this module. But its not working. Help pls
