### ISSUE TITLE
It's not working. 

### ISSUE THREAD

**Issue by ackeecheek** [samchugit/Immersive_Gestural_Nav_Bar#5]
I have miui 11 miroom rom. I i stalled it via magisk but its not working pls help me.

**Comment by samchugit** [comment]
MIUI should have customize options. You should try tweak tools specific for MIUI

**Comment by ackeecheek** [comment]
I cant find them. Can you tell me? Or send?

**Comment by samchugit** [comment]
I dont know neither. Go to MIUI forums.
