### ISSUE TITLE
hope it can automatically add padding from the layout

### ISSUE THREAD

**Issue by RA1NO3O** [samchugit/Immersive_Gestural_Nav_Bar#6]
Immersive is good , but the layout is kinda strange

**Comment by DanGLVK** [comment]
what do you mean exactly by automatically add padding from the layout?

**Comment by RA1NO3O** [comment]
> what do you mean exactly by automatically add padding from the layout? 

Sometimes the navbar just front of the bottom items(like Twitter , github app)

**Comment by DanGLVK** [comment]
> > what do you mean exactly by automatically add padding from the layout?
> 
> Sometimes the navbar just front of the bottom items(like Twitter , github app)

well in that case, there really isn't anything the dev can do, the module works by replacing the stock gesture overlays, so it can't add per app padding since overlays don't have any code, they're just replacing system resources

**Comment by RA1NO3O** [comment]
I have an idea: make navbar's black color turn to transparency

**Comment by DanGLVK** [comment]
> I have an idea: make navbar's black color turn to transparency

you mean the gesture pill or the actual navbar background?

**Comment by RA1NO3O** [comment]
> > I have an idea: make navbar's black color turn to transparency
> 
> you mean the gesture pill or the actual navbar background? 

Navbar background

**Comment by DanGLVK** [comment]
> > you mean the gesture pill or the actual navbar background?
> 
> Navbar background

Well there is simply no way to do that, there's nothing behind the navbar, it pushes the entire app upwards if it's present

**Comment by RA1NO3O** [comment]
I got that, thanks for replying🙏
